/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 shirt.glb -t -k -K 
*/

import React, { useImperativeHandle, useMemo, useState } from 'react';
import * as THREE from 'three';

import { use3dSelectedOption } from '@/hooks/api/use-3d-selected-option';
import { useSelectedProduct } from '@/hooks/api/use-selected-product';

import { useModel, useButtonHoleMaterial, useLabelMaterial, useFabricMaterial, useEmbroideryMaterial } from './hooks';

export const Model = React.forwardRef((props: JSX.IntrinsicElements['group'], ref) => {
  const [group, setGroup] = useState<THREE.Group | null>(null);
  const { selectedProduct } = useSelectedProduct();

  const { nodes, materials } = useModel();
  const { fabricMaterial } = useFabricMaterial(selectedProduct);
  const { embroideryMaterial } = useEmbroideryMaterial();
  const { buttonholeMaterial } = useButtonHoleMaterial();
  const { labelMaterial } = useLabelMaterial();

  const activeCollar = use3dSelectedOption('5400').data?.option?.code;
  const activeCuffs = use3dSelectedOption('5500').data?.option?.code;

  const activePlacket = use3dSelectedOption('5900').data?.option?.code;
  const activeChestPocket = use3dSelectedOption('6000').data?.option?.code;
  const activeEmbroideryLocation = use3dSelectedOption('7000').data?.option?.code;

  const size = useMemo(() => {
    if (!group) return 0;
    const bb = new THREE.Box3().setFromObject(group);

    return { width: bb.max.x - bb.min.x, height: bb.max.y - bb.min.y };
  }, [group]);

  useImperativeHandle(ref, () => ({ ref: group, size }));

  return (
    <>
      <group ref={(ref) => setGroup(ref)} {...props} dispose={null}>
        <group name='Scene'>
          <group name='Scene_Collection'>
            <group name='5400'>
              <group name='33000' visible={activeCollar == '33000'}>
                <mesh geometry={nodes.Buttonhole.geometry} material={buttonholeMaterial} name='Buttonhole' />
                <mesh geometry={nodes.Button.geometry} material={materials.ButtonMaterial} name='Button' />
                <mesh
                  geometry={nodes.ButtonThread.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread'
                />
                <mesh geometry={nodes.Fabric001.geometry} material={fabricMaterial} name='Fabric001' />
              </group>
              <group name='33010' visible={activeCollar == '33010'}>
                <mesh geometry={nodes.Fabric002.geometry} material={fabricMaterial} name='Fabric002' />
                <mesh geometry={nodes.Buttonhole001.geometry} material={buttonholeMaterial} name='Buttonhole001' />
                <mesh geometry={nodes.Button001.geometry} material={materials.ButtonMaterial} name='Button001' />
                <mesh
                  geometry={nodes.ButtonThread002.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread002'
                />
              </group>
              <group name='33020' visible={activeCollar == '33020'}>
                <mesh geometry={nodes.Button002.geometry} material={materials.ButtonMaterial} name='Button002' />
                <mesh
                  geometry={nodes.ButtonThread003.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread003'
                />
                <mesh geometry={nodes.Buttonhole002.geometry} material={buttonholeMaterial} name='Buttonhole002' />
                <mesh geometry={nodes.Fabric003.geometry} material={fabricMaterial} name='Fabric003' />
              </group>
              <group name='33030' visible={activeCollar == '33030'}>
                <mesh geometry={nodes.Button003.geometry} material={materials.ButtonMaterial} name='Button003' />
                <mesh
                  geometry={nodes.ButtonThread004.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread004'
                />
                <mesh geometry={nodes.Fabric004.geometry} material={fabricMaterial} name='Fabric004' />
                <mesh geometry={nodes.Buttonhole003.geometry} material={buttonholeMaterial} name='Buttonhole003' />
              </group>
              <group name='33040' visible={activeCollar == '33040'}>
                <mesh geometry={nodes.Button004.geometry} material={materials.ButtonMaterial} name='Button004' />
                <group name='Fabric1'>
                  <mesh geometry={nodes.Tessuto.geometry} material={fabricMaterial} name='Tessuto' />
                  <mesh geometry={nodes.Tessuto_1.geometry} material={nodes.Tessuto_1.material} name='Tessuto_1' />
                </group>
                <mesh geometry={nodes.Buttonhole004.geometry} material={buttonholeMaterial} name='Buttonhole004' />
                <mesh
                  geometry={nodes.ButtonThread005.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread005'
                />
              </group>
              <group name='33050' visible={activeCollar == '33050'}>
                <mesh geometry={nodes.Button005.geometry} material={materials.ButtonMaterial} name='Button005' />
                <mesh geometry={nodes.Fabric005.geometry} material={fabricMaterial} name='Fabric005' />
                <mesh
                  geometry={nodes.ButtonThread006.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread006'
                />
                <mesh geometry={nodes.Buttonhole005.geometry} material={buttonholeMaterial} name='Buttonhole005' />
              </group>
              <group name='33060' visible={activeCollar == '33060'}>
                <mesh
                  geometry={nodes.ButtonThread007.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread007'
                />
                <mesh geometry={nodes.Buttonhole006.geometry} material={buttonholeMaterial} name='Buttonhole006' />
                <mesh geometry={nodes.Button006.geometry} material={materials.ButtonMaterial} name='Button006' />
                <mesh geometry={nodes.Fabric006.geometry} material={fabricMaterial} name='Fabric006' />
              </group>
              <group name='33070' visible={activeCollar == '33070'}>
                <mesh geometry={nodes.Fabric007.geometry} material={fabricMaterial} name='Fabric007' />
                <mesh geometry={nodes.Buttonhole007.geometry} material={buttonholeMaterial} name='Buttonhole007' />
                <mesh
                  geometry={nodes.ButtonThread008.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread008'
                />
                <mesh geometry={nodes.Button007.geometry} material={materials.ButtonMaterial} name='Button007' />
              </group>
              <group name='33080' visible={activeCollar == '33080'}>
                <mesh geometry={nodes.Buttonhole008.geometry} material={buttonholeMaterial} name='Buttonhole008' />
                <mesh geometry={nodes.Button008.geometry} material={materials.ButtonMaterial} name='Button008' />
                <mesh
                  geometry={nodes.ButtonThread009.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread009'
                />
                <mesh geometry={nodes.Fabric008.geometry} material={fabricMaterial} name='Fabric008' />
              </group>
            </group>
            <group name='5500'>
              <group name='34000' visible={activeCuffs == '34000'}>
                <mesh geometry={nodes.Fabric009.geometry} material={fabricMaterial} name='Fabric009' />
                <mesh geometry={nodes.Button009.geometry} material={materials.ButtonMaterial} name='Button009' />
                <mesh
                  geometry={nodes.ButtonThread010.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread010'
                />
                <mesh
                  geometry={nodes.Embroidery3.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh geometry={nodes.Buttonhole009.geometry} material={buttonholeMaterial} name='Buttonhole009' />
                <mesh
                  geometry={nodes.Embroidery4.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4'
                  visible={activeEmbroideryLocation == '40040'}
                />
              </group>
              <group name='34010' visible={activeCuffs == '34010'}>
                <mesh geometry={nodes.Fabric010.geometry} material={fabricMaterial} name='Fabric010' />
                <mesh
                  geometry={nodes.Embroidery3001.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3001'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh
                  geometry={nodes.Embroidery4001.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4001'
                  visible={activeEmbroideryLocation == '40040'}
                />
                <mesh geometry={nodes.Button010.geometry} material={materials.ButtonMaterial} name='Button010' />
                <mesh geometry={nodes.Buttonhole010.geometry} material={buttonholeMaterial} name='Buttonhole010' />
                <mesh
                  geometry={nodes.ButtonThread011.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread011'
                />
              </group>
              <group name='34020' visible={activeCuffs == '34020'}>
                <mesh geometry={nodes.Button011.geometry} material={materials.ButtonMaterial} name='Button011' />
                <mesh
                  geometry={nodes.ButtonThread012.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread012'
                />
                <mesh geometry={nodes.Fabric011.geometry} material={fabricMaterial} name='Fabric011' />
                <mesh geometry={nodes.Buttonhole011.geometry} material={buttonholeMaterial} name='Buttonhole011' />
                <mesh
                  geometry={nodes.Embroidery3002.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3002'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh
                  geometry={nodes.Embroidery4002.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4002'
                  visible={activeEmbroideryLocation == '40040'}
                />
              </group>
              <group name='34030' visible={activeCuffs == '34030'}>
                <mesh
                  geometry={nodes.ButtonThread013.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread013'
                />
                <mesh geometry={nodes.Fabric012.geometry} material={fabricMaterial} name='Fabric012' />
                <mesh geometry={nodes.Cufflinks.geometry} material={materials.CufflinksMaterial} name='Cufflinks' />
                <mesh
                  geometry={nodes.Embroidery3003.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3003'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh
                  geometry={nodes.Embroidery4003.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4003'
                  visible={activeEmbroideryLocation == '40040'}
                />
                <mesh geometry={nodes.Button012.geometry} material={materials.ButtonMaterial} name='Button012' />
              </group>
              <group name='34040' visible={activeCuffs == '34040'}>
                <mesh
                  geometry={nodes.Cufflinks001.geometry}
                  material={materials.CufflinksMaterial}
                  name='Cufflinks001'
                />
                <mesh geometry={nodes.Button013.geometry} material={materials.ButtonMaterial} name='Button013' />
                <mesh
                  geometry={nodes.Embroidery3004.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3004'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh
                  geometry={nodes.Embroidery4004.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4004'
                  visible={activeEmbroideryLocation == '40040'}
                />
                <mesh
                  geometry={nodes.ButtonThread014.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread014'
                />
                <mesh geometry={nodes.Fabric013.geometry} material={fabricMaterial} name='Fabric013' />
              </group>
              <group name='34050' visible={activeCuffs == '34050'}>
                <mesh
                  geometry={nodes.Cufflinks002.geometry}
                  material={materials.CufflinksMaterial}
                  name='Cufflinks002'
                />
                <mesh
                  geometry={nodes.ButtonThread015.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread015'
                />
                <mesh
                  geometry={nodes.Embroidery4005.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4005'
                  visible={activeEmbroideryLocation == '40040'}
                />
                <mesh geometry={nodes.Fabric014.geometry} material={fabricMaterial} name='Fabric014' />
                <mesh
                  geometry={nodes.Embroidery3005.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3005'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh geometry={nodes.Button014.geometry} material={materials.ButtonMaterial} name='Button014' />
              </group>
              <group name='34060' visible={activeCuffs == '34060'}>
                <mesh geometry={nodes.Fabric015.geometry} material={fabricMaterial} name='Fabric015' />
                <mesh
                  geometry={nodes.Cufflinks003.geometry}
                  material={materials.CufflinksMaterial}
                  name='Cufflinks003'
                />
                <mesh
                  geometry={nodes.ButtonThread016.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread016'
                />
                <mesh
                  geometry={nodes.Embroidery3006.geometry}
                  material={embroideryMaterial}
                  name='Embroidery3006'
                  visible={activeEmbroideryLocation == '40030'}
                />
                <mesh
                  geometry={nodes.Embroidery4006.geometry}
                  material={embroideryMaterial}
                  name='Embroidery4006'
                  visible={activeEmbroideryLocation == '40040'}
                />
                <mesh geometry={nodes.Button015.geometry} material={materials.ButtonMaterial} name='Button015' />
              </group>
            </group>
            <group name='5900'>
              <group name='38000' visible={activePlacket == '38000'}>
                <mesh geometry={nodes.Fabric016.geometry} material={fabricMaterial} name='Fabric016' />
                <mesh geometry={nodes.Buttonhole012.geometry} material={buttonholeMaterial} name='Buttonhole012' />
                <mesh geometry={nodes.Button016.geometry} material={materials.ButtonMaterial} name='Button016' />
                <mesh
                  geometry={nodes.Embroidery2.geometry}
                  material={embroideryMaterial}
                  name='Embroidery2'
                  visible={activeEmbroideryLocation == '40020'}
                />
                <mesh
                  geometry={nodes.ButtonThread017.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread017'
                />
                <mesh
                  geometry={nodes.Embroidery1.geometry}
                  material={embroideryMaterial}
                  name='Embroidery1'
                  visible={activeEmbroideryLocation == '40010'}
                />
              </group>
              <group name='38010' visible={activePlacket == '38010'}>
                <mesh
                  geometry={nodes.ButtonThread018.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread018'
                />
                <mesh geometry={nodes.Fabric017.geometry} material={fabricMaterial} name='Fabric017' />
                <mesh geometry={nodes.Button017.geometry} material={materials.ButtonMaterial} name='Button017' />
                <mesh geometry={nodes.Buttonhole013.geometry} material={buttonholeMaterial} name='Buttonhole013' />
                <mesh
                  geometry={nodes.Embroidery2001.geometry}
                  material={embroideryMaterial}
                  name='Embroidery2001'
                  visible={activeEmbroideryLocation == '40020'}
                />
                <mesh
                  geometry={nodes.Embroidery1001.geometry}
                  material={embroideryMaterial}
                  name='Embroidery1001'
                  visible={activeEmbroideryLocation == '40010'}
                />
              </group>
              <group name='38020' visible={activePlacket == '38020'}>
                <mesh geometry={nodes.Fabric018.geometry} material={fabricMaterial} name='Fabric018' />
                <mesh geometry={nodes.Button018.geometry} material={materials.ButtonMaterial} name='Button018' />
                <mesh geometry={nodes.Buttonhole014.geometry} material={buttonholeMaterial} name='Buttonhole014' />
                <mesh
                  geometry={nodes.ButtonThread019.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread019'
                />
                <mesh
                  geometry={nodes.Embroidery2002.geometry}
                  material={embroideryMaterial}
                  name='Embroidery2002'
                  visible={activeEmbroideryLocation == '40020'}
                />
                <mesh
                  geometry={nodes.Embroidery1002.geometry}
                  material={embroideryMaterial}
                  name='Embroidery1002'
                  visible={activeEmbroideryLocation == '40010'}
                />
              </group>
              <group name='38030' visible={activePlacket == '38030'}>
                <mesh geometry={nodes.Fabric019.geometry} material={fabricMaterial} name='Fabric019' />
                <mesh geometry={nodes.Button019.geometry} material={materials.ButtonMaterial} name='Button019' />
                <mesh geometry={nodes.Buttonhole015.geometry} material={buttonholeMaterial} name='Buttonhole015' />
                <mesh
                  geometry={nodes.ButtonThread001.geometry}
                  material={materials.ButtonThreadMaterial}
                  name='ButtonThread001'
                />
                <mesh
                  geometry={nodes.Embroidery2003.geometry}
                  material={embroideryMaterial}
                  name='Embroidery2003'
                  visible={activeEmbroideryLocation == '40020'}
                />
                <mesh
                  geometry={nodes.Embroidery1003.geometry}
                  material={embroideryMaterial}
                  name='Embroidery1003'
                  visible={activeEmbroideryLocation == '40010'}
                />
              </group>
            </group>
            <group name='6000'>
              <group name='39020' visible={activeChestPocket == '39020'}>
                <mesh geometry={nodes.Fabric021.geometry} material={fabricMaterial} name='Fabric021' />
              </group>
              <group name='39010' visible={activeChestPocket == '39010'}>
                <mesh geometry={nodes.Fabric020.geometry} material={fabricMaterial} name='Fabric020' />
              </group>
            </group>
            <mesh geometry={nodes.Label.geometry} material={labelMaterial} name='Label' />
            <mesh geometry={nodes.Fabric.geometry} material={fabricMaterial} name='Fabric' />
          </group>
        </group>
      </group>
    </>
  );
});

Model.displayName = 'Model';
